name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check / lint
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run test

      - name: Enforce 80% line coverage gate
        shell: bash
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            COVERAGE=$(node -pe "require('./coverage/coverage-summary.json').total.lines.pct")
            echo "Total line coverage => $COVERAGE%"
            if [ "${COVERAGE%%.*}" -lt 80 ]; then
              echo "Coverage threshold not met (>=80%)"
              exit 1
            fi
          else
            echo "Coverage summary missing, skipping coverage gate."
          fi 